### ISSUE TITLE
Nos animamos a echarlo a andar?

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcas-s3-evaluacion-intermedia-SandraCGarcia#1]
Para empezar tendríamos que:

1. Pasar el array a index.js
2. Indentar todo el código
3. Ver si estamos pasando los props correctos
4. BONUS: nos animamos a hacer un componente para el ul y el li principal y uno para la card?

**Comment by SandraCGarcia** [comment]
Terminado:
1. ok
2. ok
3. ok
4. ok

Me queda terminar los estilos :)
